apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8095
              name: http
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8095
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8095
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: kafka-lab
spec:
  selector:
    app: consumer
  ports:
    - name: http
      port: 8095
      targetPort: 8095
